# Többdimenziós tömbök kezelése a NumPy-ben

## Fizika informatikusoknak géptermi gyakorlat

### v 2026/0.9

Ez a notebook bevezetés a NumPy többdimenziós tömb kezelő rutinjaiba. A példák mind kétdimenziós tömbökre vonatkoznak, de hasonlóan akárhány dimenzióra is működnének. 

Itt csak azokat a funkciókat ismertetjük, melyeket felhasználunk a későbbiekben a tárgyból.

In [1]:
import numpy as np    
import matplotlib.pyplot as plt
%matplotlib inline    

## 2D NumPy tömbök létrehozása

In [2]:
# létrehozás listák listájából
aa_list= [ [1, 2, 3, 4] ,
           [5, 6, 7, 8] 
         ]

aa=np.array(aa_list, dtype=np.float64)

print("A tömb elemei :\n", aa)
print("A tömb méretei:",aa.shape)

A tömb elemei :
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
A tömb méretei: (2, 4)


In [3]:
# 0-val feltöltött tömb létrehozása
zz=np.zeros((2,3), np.int32)
print(zz)

[[0 0 0]
 [0 0 0]]


In [4]:
# 0-val feltöltött, másik tömbhöz hasonló létrehozása:
zzaa=np.zeros_like(aa)
print(zzaa)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
# komplett másolat létrehozása:
cc=aa.copy()
print(cc)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [6]:
# sorfolytonos megadásból 2d tömb a reshape paranccsal:
dd=np.reshape([10,20,30,40,50,60], (2,3))
print(dd)

[[10 20 30]
 [40 50 60]]


In [7]:
# 2d tömbből sorfolytonossá alakítás:
ss=dd.flatten()
print(ss)

[10 20 30 40 50 60]


## Méret lekérdezés

In [8]:
print("aa méretei:", aa.shape)
print("dd méretei:", dd.shape)

aa méretei: (2, 4)
dd méretei: (2, 3)


In [9]:
print("aa sorainak száma:", aa.shape[0])
print("aa oszlopainak száma:", aa.shape[1])

aa sorainak száma: 2
aa oszlopainak száma: 4


In [10]:
print("aa elemeinek száma:", aa.size)

aa elemeinek száma: 8


In [11]:
# A len csak a sorok számát (0. dimenzió) adja meg:
print("aa sorainak száma:", len(aa))
print("dd sorainak száma:", len(dd))

aa sorainak száma: 2
dd sorainak száma: 2


## Műveletek 2d NumPy tömbökkel

In [12]:
# Az egyszerű vektorizálás könnyen működik:
bb=aa**2+3
print(bb)

[[ 4.  7. 12. 19.]
 [28. 39. 52. 67.]]


In [13]:
# Lehet csak bizonyos sorokra vagy oszlopokra hivatkozni
# Első, azaz 0-s sorszámú sor, minden oszlop
print("Első sor:\n",bb[0,:])
# utolsó oszlop:
print("Utolsó oszlop:\n",bb[:,-1])

Első sor:
 [ 4.  7. 12. 19.]
Utolsó oszlop:
 [19. 67.]


In [14]:
# értékadással is működik:
# minden második oszlop nullázása
bb[:,::2]=0
print(bb)

[[ 0.  7.  0. 19.]
 [ 0. 39.  0. 67.]]


In [15]:
hh1=np.reshape([8.0,-1,4,8,-4,5], (2,3))
hh2=np.reshape([-8.0,+3,2,7,0,5], (2,3))

print("Két teszt-tömb:")
print(hh1)
print(hh2)

Két teszt-tömb:
[[ 8. -1.  4.]
 [ 8. -4.  5.]]
[[-8.  3.  2.]
 [ 7.  0.  5.]]


In [16]:
# elemenkénti összegek azonos méretű tömbö közt:
hh_sum=hh1+hh2
print(hh_sum)

[[ 0.  2.  6.]
 [15. -4. 10.]]


In [17]:
# elemenkénti maximumok:
print(np.maximum(hh1, hh2))

[[8. 3. 4.]
 [8. 0. 5.]]


In [18]:
# Az egyik elem lehet egy skalár is:

print("hh1 pi-szerese:")
print(np.pi*hh1)

print("hh1 nemnegatív elemei:")
print(np.maximum(hh1, 0))

hh1 pi-szerese:
[[ 25.13274123  -3.14159265  12.56637061]
 [ 25.13274123 -12.56637061  15.70796327]]
hh1 nemnegatív elemei:
[[8. 0. 4.]
 [8. 0. 5.]]


## Az axis-ek koncepciója

In [19]:
# NumPy többdimenziós tömbök: tengelyek mentén rendezett adatok.
# 2D tömb: 0-s axis=sor, 1-es axis=oszlop
# számolási rutinok vonatkozhatnak csak bizonyos axis-ekre

In [20]:
# gyakorló tömb:
aa_list= [ 
           [1, 2, 3, 4] ,
           [5, 6, 7, 8] 
         ]

aa=np.array(aa_list, dtype=np.float64)

In [21]:
# Minden elem összege: egy szám
print(aa.sum())

36.0


In [22]:
# összegzés a 0-s axis mentén: annyi szám, ahány oszlop, sorok "összeejtése"
print(aa.sum(axis=0))

[ 6.  8. 10. 12.]


In [23]:
# összegzés a 1-s axis mentén: annyi szám, ahány sor, oszlopok "összeejtése"
print(aa.sum(axis=1))

[10. 26.]


In [24]:
# sorok átlaga
print(aa.mean(axis=1))

[2.5 6.5]


In [25]:
# oszlopok négyzetösszegéből vont gyök:
print((aa**2).sum(axis=0)**0.5)
# Ezt használni fogjuk vektorok abszolút értékének számolásakor

[5.09901951 6.32455532 7.61577311 8.94427191]


## Boolean értékek felhasználása

Az 1D esetben tanultakhoz hasonlóan.

In [26]:
# aa elemei oszthatók-e 3-mal?
map_3n= (aa%3==0)
print(map_3n)
# kimenet: boolean "térkép" arról, hol igaz a feltétel

[[False False  True False]
 [False  True False False]]


In [27]:
# Csak a 3-mal sztható elemek print-elése:
print(aa[map_3n])

[3. 6.]


In [28]:
# Ilyen boolean tömb felhasználható értékadásra is:
# A 3-mal osztható elemeket elosztjuk 3-mal
aa[map_3n] /= 3 
print(aa)

[[1. 2. 1. 4.]
 [5. 2. 7. 8.]]


In [29]:
# Ahol True van, azok tömbje megkapható az argwhere paranccsal:
np.argwhere(map_3n)

array([[0, 2],
       [1, 1]])

In [30]:
# hol nagyobb hh1, mint hh2?
hh1_dominates=hh1>hh2
print(hh1_dominates)

[[ True False  True]
 [ True False False]]


In [31]:
print("hh1:\n", hh1)
print("hh2:\n", hh2)

print("hh1 nagyobb elemet tartalmaz, mint hh2 az alábbi pozíciókban:")
for arg in np.argwhere(hh1_dominates):
    print(arg)

hh1:
 [[ 8. -1.  4.]
 [ 8. -4.  5.]]
hh2:
 [[-8.  3.  2.]
 [ 7.  0.  5.]]
hh1 nagyobb elemet tartalmaz, mint hh2 az alábbi pozíciókban:
[0 0]
[0 2]
[1 0]


## Gyakorló feladatok

Mivel ebben nincs elvi újdonság a korábban tanultakhoz képest, megadom mindegyik megoldását. A fizika példákra való alkalmazásokban lesz idő a saját feladatmegoldásra. Mostani cél: mindegyiket megérteni.

In [32]:
ff_list=[[0, 1], [1, 4], [2, 5], [3, 9]]
ff=np.array(ff_list, np.float64)
print(ff)

[[0. 1.]
 [1. 4.]
 [2. 5.]
 [3. 9.]]


**1. feladat:**

Írja ki, hogy ff hány sorból áll!

In [33]:
print("Sorok száma:",ff.shape[0])

Sorok száma: 4


**2. feladat**

Adja meg ff sorainak összegét!

In [34]:
ff.sum(axis=1)

array([ 1.,  5.,  7., 12.])

**3. feladat**

Ha ff nem más, mint 4 db 2 dimenziós vektor, akkor mi ezen vektorok hossza?

In [35]:
print(((ff**2).sum(axis=1))**0.5)

[1.         4.12310563 5.38516481 9.48683298]


**4. feladat**

Ha ff nem más, mint 4 db 2 dimenziós vektor, akkor melyik ezek közül a legnagyobb hosszúságú?

In [36]:
ff_abs=((ff**2).sum(axis=1))**0.5
print("A legnagyobb absz. értékű vektor indexe:",ff_abs.argmax())

A legnagyobb absz. értékű vektor indexe: 3


**5. feladat**

ff mely soraiban fordul elő, hogy az 1-es komponens nagyobb 4-nél?

In [37]:
print("A következő sorokban nagyobb az 1-es komponens 4-nél:")
print(np.argwhere(ff[:,1]>4).flatten())

A következő sorokban nagyobb az 1-es komponens 4-nél:
[2 3]


**6. feladat**

ff mely soraiban fordul elő, hogy az 1-es komponens nagyobb a 0-s kétszeresénél?

In [38]:
print("A következő sorokban nagyobb az 1-es komponens a 0-s kétszeresénél:")
print(np.argwhere(  ff[:,1] > ff[:,0]*2  ).flatten())

A következő sorokban nagyobb az 1-es komponens a 0-s kétszeresénél:
[0 1 2 3]


**7. feladat**

Nullázza ff azon elemeit, melyek nagyobbak ff átlagának felénél!

In [39]:
average=ff.mean()

ff[ ff>average/2 ] = 0

print(ff)

[[0. 1.]
 [1. 0.]
 [0. 0.]
 [0. 0.]]


# Új NumPy eljárások

   * `aa.size`: tömb elemeinek száma
   * `np.maximum(aa, bb)`: a két tömb elemenkénti maximuma
   * `np.reshape(tömb_vagy_lista, shape)`: a megadott tömb vagy lista elemeből a `shape`-nek megfelelő átrendezést hoz létre
